// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfXdU8w4HMqonpKjE6GhDqBRfvwT6_NbA',
    appId: '1:994497442211:web:e3d38bc167911f03996a16',
    messagingSenderId: '994497442211',
    projectId: 'crud-app-e1cef',
    authDomain: 'crud-app-e1cef.firebaseapp.com',
    storageBucket: 'crud-app-e1cef.appspot.com',
    measurementId: 'G-VZHZL1XC96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHVBcz3jp40OQrB4Z5sURbduAzryJUKW8',
    appId: '1:994497442211:android:b5540b262cedd926996a16',
    messagingSenderId: '994497442211',
    projectId: 'crud-app-e1cef',
    storageBucket: 'crud-app-e1cef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFzr-YJBr_dQQSr6oPm-HDI_rE4Ci3FRs',
    appId: '1:994497442211:ios:9ba4ea8c9b5ec615996a16',
    messagingSenderId: '994497442211',
    projectId: 'crud-app-e1cef',
    storageBucket: 'crud-app-e1cef.appspot.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFzr-YJBr_dQQSr6oPm-HDI_rE4Ci3FRs',
    appId: '1:994497442211:ios:9ba4ea8c9b5ec615996a16',
    messagingSenderId: '994497442211',
    projectId: 'crud-app-e1cef',
    storageBucket: 'crud-app-e1cef.appspot.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfXdU8w4HMqonpKjE6GhDqBRfvwT6_NbA',
    appId: '1:994497442211:web:4eca18a28fe91890996a16',
    messagingSenderId: '994497442211',
    projectId: 'crud-app-e1cef',
    authDomain: 'crud-app-e1cef.firebaseapp.com',
    storageBucket: 'crud-app-e1cef.appspot.com',
    measurementId: 'G-DJZES69HX9',
  );

}